"use client";

import * as React from "react";
import {
  FileCheck2,
  Sparkles,
  Download,
  FileText,
  CheckCircle2,
  AlertCircle,
  TrendingUp,
  Share2,
  Calendar,
  Layers,
  ArrowRight,
  Code2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { jsPDF } from "jspdf";

export default function ReportsPage() {
  const [reports, setReports] = React.useState<any[]>([]);
  const [isGenerating, setIsGenerating] = React.useState(false);
  const [activeReport, setActiveReport] = React.useState<any>(null);

  const fetchReports = async () => {
    try {
      const res = await fetch("/api/ai/reports");
      const json = await res.json();
      if (json.reports && json.reports.length > 0) {
        setReports(json.reports);
        if (!activeReport) setActiveReport(json.reports[0]);
      }
    } catch (e) {
      console.error(e);
    }
  };

  React.useEffect(() => {
    fetchReports();
  }, []);

  const handleGenerateReport = async () => {
    setIsGenerating(true);
    try {
      const res = await fetch("/api/ai/reports", { method: "POST" });
      const json = await res.json();
      if (json.report) {
        setReports((prev) => [json.report, ...prev]);
        setActiveReport(json.report);
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsGenerating(false);
    }
  };

  const handleExportPDF = () => {
    if (!activeReport) return;
    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(activeReport.title, 14, 20);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Period: ${activeReport.period} | Generated by adAIPROMORA (Developed by Satkuri Kailash)`, 14, 28);

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("Executive Summary:", 14, 40);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    const splitSummary = doc.splitTextToSize(activeReport.executiveSummary, 180);
    doc.text(splitSummary, 14, 48);

    doc.save(`aipromora-report-${Date.now()}.pdf`);
  };

  const handleExportJSON = () => {
    if (!activeReport) return;
    const blob = new Blob([JSON.stringify(activeReport, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `marketing-report-${Date.now()}.json`;
    a.click();
  };

  const parseJsonSafe = (val: any) => {
    if (!val) return null;
    if (typeof val === "string") {
      try {
        return JSON.parse(val);
      } catch (e) {
        return null;
      }
    }
    return val;
  };

  const insights = parseJsonSafe(activeReport?.insightsJson);
  const recommendations = parseJsonSafe(activeReport?.recommendationsJson);
  const metrics = parseJsonSafe(activeReport?.metricsJson);

  return (
    <div className="space-y-6 animate-in fade-in duration-200">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 pb-5 dark:border-slate-800">
        <div>
          <div className="inline-flex items-center gap-1.5 rounded-full bg-teal-50 px-2.5 py-0.5 text-xs font-semibold text-teal-700 dark:bg-teal-950/60 dark:text-teal-300 mb-1 border border-teal-200 dark:border-teal-800">
            <FileCheck2 className="h-3 w-3" />
            <span>AI Executive Reports</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-slate-900 dark:text-slate-100">
            Strategic Marketing Attribution Reports
          </h1>
          <p className="text-xs text-slate-500">
            AI synthesizes performance data into executive takeaways, what worked, channel attribution, and next month action items.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <Button
            onClick={handleGenerateReport}
            disabled={isGenerating}
            variant="gradient"
            size="sm"
            className="h-10 px-4 text-xs font-bold gap-2 shadow-md"
          >
            <Sparkles className="h-4 w-4" />
            <span>{isGenerating ? "Synthesizing AI Report..." : "Generate Fresh AI Report"}</span>
          </Button>
        </div>
      </div>

      {/* Two Column Layout: Report History & Active Document */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Reports Archive */}
        <div className="lg:col-span-4 space-y-3">
          <div className="text-xs font-semibold text-slate-500 uppercase tracking-wider px-1">
            Generated Reports ({reports.length})
          </div>
          {reports.map((rep) => (
            <button
              key={rep.id}
              onClick={() => setActiveReport(rep)}
              className={`w-full text-left p-4 rounded-xl border transition-all space-y-1.5 ${
                activeReport?.id === rep.id
                  ? "border-teal-500 bg-teal-50/40 dark:bg-teal-950/30 shadow-sm"
                  : "border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 hover:border-slate-300"
              }`}
            >
              <div className="font-bold text-sm text-slate-900 dark:text-slate-100 line-clamp-1">
                {rep.title}
              </div>
              <div className="flex items-center justify-between text-xs text-slate-500">
                <span>{rep.period}</span>
                <span className="font-mono text-[10px]">{new Date(rep.createdAt).toLocaleDateString()}</span>
              </div>
            </button>
          ))}
        </div>

        {/* Active Report View */}
        <div className="lg:col-span-8 space-y-6">
          {activeReport ? (
            <Card className="shadow-sm border-slate-200 dark:border-slate-800">
              {/* Document Actions Bar */}
              <div className="flex flex-col sm:flex-row sm:items-center justify-between p-6 border-b border-slate-100 dark:border-slate-800 gap-4 bg-slate-50/50 dark:bg-slate-900/30">
                <div>
                  <h2 className="text-lg font-bold text-slate-900 dark:text-slate-100">
                    {activeReport.title}
                  </h2>
                  <p className="text-xs text-slate-500 mt-0.5">
                    Period: {activeReport.period} • Verified attribution model
                  </p>
                </div>

                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleExportPDF}
                    className="h-8 text-xs gap-1.5"
                  >
                    <Download className="h-3.5 w-3.5" /> PDF
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={handleExportJSON}
                    className="h-8 text-xs gap-1.5"
                  >
                    <Code2 className="h-3.5 w-3.5" /> JSON
                  </Button>
                </div>
              </div>

              <CardContent className="p-6 space-y-6 text-xs leading-relaxed">
                {/* Executive Summary */}
                <div className="p-4 rounded-xl bg-teal-50/60 dark:bg-teal-950/40 border border-teal-200 dark:border-teal-800 space-y-1.5">
                  <div className="font-bold text-teal-950 dark:text-teal-200 uppercase tracking-wider text-[11px]">
                    Executive Summary:
                  </div>
                  <p className="text-slate-800 dark:text-slate-200 text-sm">
                    {activeReport.executiveSummary}
                  </p>
                </div>

                {/* What Worked vs What Didn't */}
                {insights && (
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                    <div className="space-y-2">
                      <div className="font-bold text-emerald-700 dark:text-emerald-400 flex items-center gap-1.5 text-sm">
                        <CheckCircle2 className="h-4 w-4" /> What Worked & Scaled
                      </div>
                      <div className="space-y-2">
                        {insights.whatWorked?.map((item: string, idx: number) => (
                          <div key={idx} className="p-3 rounded-lg bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 text-slate-700 dark:text-slate-300">
                            • {item}
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <div className="font-bold text-amber-600 dark:text-amber-400 flex items-center gap-1.5 text-sm">
                        <AlertCircle className="h-4 w-4" /> Bottlenecks & Leaks
                      </div>
                      <div className="space-y-2">
                        {insights.whatDidNotWork?.map((item: string, idx: number) => (
                          <div key={idx} className="p-3 rounded-lg bg-amber-50/40 dark:bg-amber-950/20 border border-amber-100 dark:border-amber-900/40 text-slate-700 dark:text-slate-300">
                            • {item}
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                {/* Tactical Action Plan */}
                {recommendations && (
                  <div className="space-y-2 pt-2 border-t border-slate-100 dark:border-slate-800">
                    <div className="font-bold text-slate-900 dark:text-slate-100 text-sm flex items-center gap-1.5">
                      <Sparkles className="h-4 w-4 text-teal-600" /> Recommended Action Items for Next Sprint
                    </div>
                    <div className="space-y-2">
                      {recommendations.map((rec: string, idx: number) => (
                        <div key={idx} className="p-3 rounded-xl bg-slate-50 dark:bg-slate-900 border border-slate-100 dark:border-slate-800 flex items-start gap-2.5">
                          <span className="font-bold text-teal-600">#{idx + 1}</span>
                          <span className="text-slate-800 dark:text-slate-200">{rec}</span>
                        </div>
                      ))}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          ) : (
            <div className="h-80 flex flex-col items-center justify-center text-center text-slate-400">
              <FileCheck2 className="h-10 w-10 text-slate-300 dark:text-slate-700 mb-2" />
              <p className="text-xs">Click Generate Fresh AI Report to synthesize marketing metrics.</p>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
